export const IMPORTCAR_SUCCESS = 'IMPORTCAR_SUCCESS'
export const IMPORTCAR_ERROR = 'IMPORTCAR_ERROR'
export const IMPORTCAR_FAILED = 'IMPORTCAR_FAILED'
export const IMPORTCAR_WAITING = 'IMPORTCAR_WAITING'
export const IMPORTCAR_SERVICEERROR = 'IMPORTCAR_SERVICEERROR'
export const RESET_IMPORTCAR = 'RESET_IMPORTCAR'





