export const SEARCH_VINLIST_SUCCESS = 'SEARCH_VINLIST_SUCCESS'
export const SEARCH_VINLIST_FAILED = 'SEARCH_VINLIST_FAILED'
export const SEARCH_VINLIST_WAITING = 'SEARCH_VINLIST_WAITING'
export const SEARCH_VINLIST_ERROR = 'SEARCH_VINLIST_ERROR'
export const SEARCH_VINLIST_SERVICEERROR = 'SEARCH_VINLIST_SERVICEERROR'
export const RESET_SEARCH_VINLIST_STATUS = 'RESET_SEARCH_VINLIST_STATUS'
export const RESET_SEARCH_VINLIST = 'RESET_SEARCH_VINLIST'


