export const GET_ENTRUSTS_SUCCESS = 'GET_ENTRUSTS_SUCCESS'
export const GET_ENTRUSTS_FAILED = 'GET_ENTRUSTS_FAILED'
export const GET_ENTRUSTS_WAITING = 'GET_ENTRUSTS_WAITING'
export const GET_ENTRUSTS_ERROR = 'GET_ENTRUSTS_ERROR'
export const GET_ENTRUSTS_SERVICEERROR = 'GET_ENTRUSTS_SERVICEERROR'

